#!/bin/sh

#latexmk -pvc -pdf "$1" </dev/null
cmd='latexmk -pvc -outdir=target --pdf'

if [ "$1" = "--watch" ]; then
  $cmd
  while inotifywait -e close_write -e modify content.tex references.bib graphics/sketches/*; do
		$cmd
	done;
else
  $cmd
fi
