#!/bin/sh

#latexmk -pvc -pdf "$1" </dev/null
cmd1='latexmk -pvc -xelatex -interaction=nonstopmode -outdir=target --pdf'
cmd2='latexmk -outdir=target --pdf'

if [ "$1" = "--watch" ]; then
  $cmd1
  while inotifywait -e close_write -e modify content.tex references.bib graphics/sketches/*; do
		$cmd
	done;
else
  $cmd2
fi
